runtime: nodejs16 # or another supported version
env: standard

instance_class: F2

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  BUCKET_NAME: "flaggle"

# handlers:
# - url: /.*

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
